[project]
name = "cert-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "gradio>=5.49.1",
    "langchain>=1.0.2",
    "langchain-core>=1.0.1",
    "requests>=2.32.5",
]
